name: CryptoPanic Fetcher

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install chromium

    - name: Run script
      env:
        CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
      run: |
        echo "Starting script execution..."
        node index.js
        echo "Script execution completed"
